### ISSUE TITLE
NZBget scriptpath

### ISSUE THREAD

**Issue by uffcd** [l3uddz/cloudbox#2]
Parameter Scriptpath should be AppDir (not MainDIR)

**Comment by l3uddz** [comment]
only path i change on nzbget is MainDir to /downloads/nzbget, is this not the case for you?

**Comment by uffcd** [comment]
it is. but the scripts folder is in AppDir not in the MainDir. Maybe a problem in the docker 

I need it to get the password out of the nzb filename: [https://forum.nzbget.net/viewtopic.php?t=2875]

**Comment by desimaniac** [comment]
@uffcd That is how the docker container was setup as. See [here](https://github.com/linuxserver/docker-nzbget/blob/master/root/etc/cont-init.d/30-config). Setting it to AppDir would make it unaccessible to the host. By using it with MainDir, it will be located in your downloads folder `~/downloads/nzbget/scripts`.

**Comment by l3uddz** [comment]
It's now /opt/scripts/nzb now for nzbget scripts
