### ISSUE TITLE
LocalHost

### ISSUE THREAD

**Issue by kanenses** [l3uddz/cloudbox#4]
During installing, I'am getting:

> changed: [localhost]

On the endding of installing, I'am unable to access apps on server.

I'am using Scaleway Machine VC1M (4 X86 64bit Cores / 4GB memory)

On the end of installing I'am get the follow in red:

> failed: [localhost] (item=[u'unrar', u'unzip', u'p7zip', u'python-pip', u'python3-pip', u'python-passlib', u'curl', u'sqlite3', u'vnstat', u'tree', u'lsof', u'man-db', u'ksmtuned', u'git', u'pwgen', u'rsync', u'logrotate', u'htop', u'iotop', u'nload', u'fail2ban', u'ufw', u'speedtest-cli']) => {"failed": true, "item": ["unrar", "unzip", "p7zip", "python-pip", "python3-pip", "python-passlib", "curl", "sqlite3", "vnstat", "tree", "lsof", "man-db", "ksmtuned", "git", "pwgen", "rsync", "logrotate", "htop", "iotop", "nload", "fail2ban", "ufw", "speedtest-cli"], "msg": "No package matching 'unrar' is available"}

Box have one public IP and a Private IP.

**Comment by l3uddz** [comment]
https://github.com/l3uddz/cloudbox/wiki/Prerequisites

It's not complete the wiki but you will see why it's not working. This project requires a domain.

**Comment by kanenses** [comment]
I have added a domain, in this case a subdomain ... dk.mydomain.com

:-(

**Comment by l3uddz** [comment]
Are you using Ubuntu 16.04?

**Comment by desimaniac** [comment]
@kanenses You can follow steps 1-4 of [First Time Install](https://github.com/l3uddz/cloudbox/wiki#first-time-install), since those are complete.

**Comment by kanenses** [comment]
Using ubuntu:  Ubuntu Xenial (16.04 latest) (deploy at scaleway)

**Comment by desimaniac** [comment]
Also it is helpful to see what youve done so far. You can post the screenshot here or you can copy the entire install log to pastebin and post the link here.

**Comment by l3uddz** [comment]
Are you using develop branch ? Master is out of date. Until readme is finished and pushed. But develop branch is what ppl are currently using

**Comment by kanenses** [comment]
using master, i think, but when come home, i can deploy new vm, i try with develop.

**Comment by desimaniac** [comment]
follow the wiki, it mentioned develop. when master is done, it will update to show that.

**Comment by kanenses** [comment]
so is develop, as i have follow wik, Git checkout develop? os that correct

**Comment by desimaniac** [comment]
steps 1-4, and v-viii of 5 are complete.

**Comment by kanenses** [comment]
hmmm...

strange, it seems docker as not installed by setup, indeed?

**Comment by desimaniac** [comment]
Please list the steps youve taken.

**Comment by kanenses** [comment]
exactly steps descript on your wiki... point by point
how can I have access to log?

**Comment by desimaniac** [comment]
are you on discord (the chat app)?

**Comment by kanenses** [comment]
no, but I can install it, if you what no problem
(I will start a new vm now)

**Comment by desimaniac** [comment]
Actually, install Slack, not discord.

**Comment by kanenses** [comment]
Open what team?

**Comment by kanenses** [comment]
hmm, not find you...

**Comment by desimaniac** [comment]
try typing in "cloud-box" for team.

**Comment by kanenses** [comment]
not can signup, I get: Sorry, you entered an incorrect email address or password.

**Comment by kanenses** [comment]
You need send me invite for team, or will not work

**Comment by desimaniac** [comment]
Try the link again. I updated it.

**Comment by kanenses** [comment]
You are give my own link, need to share yours

**Comment by desimaniac** [comment]
https://join.slack.com/t/cloud-box/shared_invite/MjM1NTI2OTEwMzIyLTE1MDQzOTAyNDAtYWNhOWY2NzNiZA

**Comment by l3uddz** [comment]
Issue resolved.
