### ISSUE TITLE
Threadfin

### ISSUE THREAD

**Issue by 0xW1sKy** [l3uddz/cloudbox#492]
---

**Describe the problem**
A clear and concise description of the problem you're looking to solve.

Looking for docker image for Threadfin I.e.

This appears to be the current live project for an IPTV -> Plex project to allow plex to run as a virtual cable service. Project is based on xteve. 

**Describe any solutions you think might work**
A clear and concise description of any solutions or features you've considered.

If you got the contacts would be cool to see a similar EPG & M3U proxy setup using the starr framework. 

**Additional context**

As far as I can tell Threadfin is the most popular actively maintained version of this. Although the old one was called xteve

**Comment by owine** [comment]
Cloudbox has reached end of life. Many users have migrated to Saltbox which originated as a fork. Threadfin is available there
